// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plftmtvdaednfrbdgajw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZnRtdHZkYWVkbmZyYmRnYWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzI1NDEsImV4cCI6MjA2OTk0ODU0MX0.NaDSFOYBsZiYFI2VsjE2IKS3xl5hCNc_RXupuvzzFLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});